[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
upload_speed = 57600
monitor_port = COM9
lib_deps =
    olikraus/U8g2
    bblanchon/ArduinoJson
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
build_flags =
    -I include
